[Settings]

; please note that i accedently also committed credentials/api keys in some commits. these have all been changed.

; time to backup and reboot
timeToReboot=02:59

; NAS
backupToNas=true
adressToNas="\\Nas-Rutger\home"
NasUserName=
NasPassw=

; servers
enableBackup=true
enableMinecraftServer=true
enableFactorioServer=true
checkForServerCrash=true
StopServerAfter3Crashes=true

; start server location
startMinecraftServer=C:\minecraft\Minecraft_Server_Start.bat
startFactorioServer=C:\factorio\Factorio_Server_Start.bat

; backup Folders

    ;source folders
mineCraftServerSource=C:\minecraft
factorioServerSource=C:\factorio
    ;destination folders where the backup should be placed. MAKE SURE THESE FOLDERS EXIST
minecraftServerDestination=
factorioServerDestination=
; enable discord msg's
enableDiscordMsg=true
; discord webhook, for discord Minefac msg's
webhookDiscord=https://discord.com/api/webhooks/1005162815063080970/XhWYaLLwo9OiEjKDl2zaRdnxkYeRBR4456mIf4b_Oq1DBQvPpQ_F4wqpRlkp8JAB-7fJ
