[Settings]

; please note that i accedently also committed credentials/api keys in some commits. these have all been changed.

; time to backup and reboot
timeToReboot=02:59

; NAS
backupToNas=true
adressToNas="\\Nas-Rutger\home"
NasUserName=
NasPassw=

; servers
enableBackup=true
enableMinecraftServer=true
enableFactorioServer=true
checkForServerCrash=true

; start server location
startMinecraftServer=
startFactorioServer=

; backup Folders

    ;source folders
mineCraftServerSource=C:\minecraft
factorioServerSource=C:\factorio
    ;destination folders where the backup should be placed. MAKE SURE THESE FOLDERS EXIST
minecraftServerDestination=
factorioServerDestination=
; enable discord msg's
enableDiscordMsg=false
; discord webhook, for discord Minefac msg's
webhookDiscord=
